---
title: "imperial_researchproject1"
output: html_document
date: '2024-01-05'
---

Prior to import excel file;
  questions coalesced into single columns with an answer by each patient
  start and end times converted to the same format of dd/mm/yyyy hh;mm;ss 24hr clock (with corrected from american format)
  '.' removed
  'spaces' replaced with underscores
  "Less_than_<10%", "10%-30%" changed to "<10%", "10-30%"
  "_(if_any)" dropped from religious beliefs colname


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyr)
library(readr)
library(ggplot2)
library(ggsignif)
library(broom)

setwd("~/¬Personal/¬EDU/Imperial/Research_project_1")

df <- read_csv("~/¬Personal/¬EDU/Imperial/Research_project_1/progress_excel_file_v4.csv")

dd <- read_csv("~/¬Personal/¬EDU/Imperial/Research_project_1/progress_data_dictionary.csv")

stat_stars <- data.frame(sig = c(0.0001, 0.001, 0.01, 0.05, 1),
                         star = c("****", "***", "**", "*", ""))
```

```{r knowledge score apply}
dd_knowledge <- dd[grep("knowledge", dd$type), ]
dd_knowledge <- dd_knowledge[ ,c(2, 6:7)]
dd_knowledge <- as.data.frame(dd_knowledge)

df_knowledge <- as.data.frame(df[c(1, 38:40, 53:69)]) #all knowledge questions
rownames(df_knowledge) <- df_knowledge$Respondent_ID
df_knowledge <- df_knowledge[, -1]

knowledge_response <- df_knowledge %>% 
  mutate(
    across(
      .fns = ~ case_when(
        . == "Yes" ~ 0,
        . == "Strongly_Agree" ~ 0,
        . == "Agree" ~ 0,
        . == "Somewhat_Agree" ~ 0,
        . == "No" ~ 1,
        . == "Strongly_Disagree" ~ 1,
        . == "Disagree" ~ 1,
        . == "Somewhat_Disagree" ~ 1,
        . == "Unsure" ~ 2, #unsure is always a wrong answer
        . == "Does_not_apply_to_me" ~ NA_real_
      )
    )
  )
```
```{r counting correct answers}
correct_answers <- as.numeric(dd_knowledge$answer)
correct_count <- apply(knowledge_response, 1, function(x) sum(x == correct_answers))

dfv2 <- as.data.frame(df[c(1:37, 41:52, 70:78)]) #columns apart from knowledge questions
dfv2$correct_answers <- correct_count
```

```{r visualizing knowledge data}
dfv2 <- mutate(dfv2, gp_or_patient = if_else(Collector_ID == "175862735", "gp", "patient")) 

knowledge_stats <- group_by(dfv2, gp_or_patient) %>%
  summarise(
    median = median(correct_answers, na.rm = TRUE),
    IQR_low = quantile(correct_answers, probs = 0.25, na.rm = TRUE),
    IQR_high = quantile(correct_answers, probs = 0.75, na.rm = TRUE)
    )

knowledge_stats_dr <- knowledge_stats[1, ]
knowledge_stats_pt <- knowledge_stats[2, ]
```

```{r boxplot base}
knowledge_plot <- ggplot(dfv2, 
                         aes(x = gp_or_patient, 
                             y = correct_answers, 
                             fill = gp_or_patient)) +
  
  labs(x = "Group",
       y = "Number of Correct Answers ") +
  
  scale_y_continuous(breaks = seq(min(dfv2$correct_answers), 
                                  max(dfv2$correct_answers), 
                                  by = 2))
```
```{r boxplot1}
knowledge_plot +
  
  geom_boxplot(varwidth = TRUE,
               show.legend = FALSE) +
  
  geom_signif(comparisons = list(c("gp", "patient")),
              map_signif_level = TRUE, 
              textsize = 3) +
  
  theme_minimal(base_size = 12) 
```

```{r knowledge impact on opinion with 'unsure'}
dd_opinion <- dd[grep("opinion", dd$type), ]
dd_opinion <- dd_opinion[ , c(2, 7)]
dd_opinion$qnumber <- sprintf("q%02d", 1:nrow(dd_opinion))
#to double check if same number of variables correctly selected out of dataframe 

df_opinion <- as.data.frame(df[c(1, 14, 29:37, 41:52, 70:73)])
rownames(df_opinion) <- df_opinion$Respondent_ID

opinion_response <- df_opinion[, -1]
colnames(opinion_response) <- sprintf("q%02d", 1:ncol(opinion_response))
```
```{r}
binary_opinion <- opinion_response[c(1:22)] %>% # missing percentage answers col 23:26
  mutate(
    across(
      .fns = ~ case_when(
        . == "Yes" ~ 0,
        . == "Strongly_Agree" ~ 0,
        . == "Agree" ~ 0,
        . == "Somewhat_Agree" ~ 0,
        . == "No" ~ 1,
        . == "Strongly_Disagree" ~ 1,
        . == "Disagree" ~ 1,
        . == "Somewhat_Disagree" ~ 1,
        . == "Unsure" ~ 2,
        . == "Does_not_apply_to_me" ~ NA_real_
      )
    )
  )

binary_opinion[] <- lapply(binary_opinion, factor)

dfok <- cbind(binary_opinion, correct_count)
```

```{r Multinomial Logistic Regression}
results.ok <- list()

for(i in 1:22) {
  question_col <- sprintf("q%02d", i)
  
  formula_str <- paste(question_col, "~ correct_count")
  formula_obj <- as.formula(formula_str)
  
  results.ok[[question_col]] <- glm(formula = formula_obj, 
                                    data = dfok,
                                    family = "binomial",
                                    na.action = na.omit)
}
```
```{r Odds Ratio + CI}
model_ok <- data.frame()

for (question_col in names(results.ok)) {
  
  glm_model <- results.ok[[question_col]]
  
  summary <- tidy(results.ok[[question_col]])
  summary$Question <- question_col

  model_ok <- rbind(model_ok, summary)
}

model_ok_binary <- subset(model_ok, term != "(Intercept)") # current model calculates the likelihood of answering "no" to questions, influenced by knowledge score. *-1 to inverse, showing likelihood of answering yes
model_ok_binary$estimate <- model_ok_binary$estimate * -1
model_ok_binary$OddsRatio <- exp(model_ok_binary$estimate)

model_ok_binary$LowerCI <- exp(model_ok_binary$estimate) - 
  (1.96 * model_ok_binary$std.error)
model_ok_binary$UpperCI <- exp(model_ok_binary$estimate) + 
  (1.96 * model_ok_binary$std.error)

model_ok_binary$group <- c("Increase the availability of genetic testing", #1
                           "Fear of knowing personal risk genetic results", #2
                           "Desire to know personal risk from genetic results", #3
                           "Limiting availability of genetic testing to high risk persons", #4
                           "Limiting availability of genetic testing to high risk persons", #5
                           "Genetic testing will be over the counter", #6
                           "Genetic testing will be over the counter", #7
                           "Increase the availability of genetic testing", #8
                           "Use genetic testing to improve screening/treatment", #9
                           "Increase the availability of genetic testing", #10
                           "Desire to know personal risk from genetic results", #11
                           "Use genetic testing to improve screening/treatment", #12
                           "Fear of knowing personal risk genetic results", #13
                           "Choose not to know risk of untreatable disease", #14
                           "Choose not to know risk of untreatable disease", #15
                           "Fear of knowing personal risk genetic results", #16
                           "Genetic tests will be common in the future", #17
                           "In 5 to 10 years time we will have genetic passports", #18
                           "In 5 to 10 years time genetic information will be stored in computers", #19
                           "In 5 to 10 years time all children will recieve genetic testing for risk", #20
                           "Genetic tests will impact emplyoment/insurance", #21
                           "Genetic tests will impact emplyoment/insurance") #22

dd_opinion_readable <- dd_opinion[1:22, 1] %>%
  mutate(
    across(
      everything(), ~ gsub("_", " ", .)
      )
    )

model_ok_binary$stars <-
  sapply(model_ok_binary$p.value, function(p) {
    if (is.na(p))
      return(NA)
    # Find the first instance where the p-value is less than or equal to 'sig' and return the corresponding 'star'
    star <- stat_stars$star[which(p <= stat_stars$sig)[1]]
    if (length(star) == 0)
      ""
    else
      star # If no stars are assigned, return an empty string
  })

```
```{r glm ci plot}
ggplot(model_ok_binary, 
       aes(y = reorder(group, OddsRatio), 
           x = OddsRatio, 
           xmin = LowerCI, 
           xmax = UpperCI)) +
  
  geom_linerange(aes(color = group),
                 position = position_dodge2(width = 0.5)) +
  
  geom_point(aes(color = group),
             position = position_dodge2(width = 0.5),
             size = 2)+
  
  geom_vline(xintercept = 1,
             linetype = 3) +

  labs(y = "Group of questions") +
  
  geom_text(aes(label = stars, 
                y = reorder(group, OddsRatio)),
            position = position_dodge2(width = 0.5),
            vjust = 0, 
            color = "black", 
            size = 3.8) + 
  
  theme(legend.position = "none",
        plot.title = element_text(hjust = 1.5)) +

  scale_y_discrete(labels = label_wrap_gen(width = 50))

```

```{r opinion changes % question}
percent_count <- df[1:6500, 70:73]
colnames(percent_count) <- c("Surgery", "Medication", "Lifestyle change", "Diet change")
counts_per_column <- apply(percent_count, 2, table)

counts_per_column <- as.data.frame(counts_per_column)
counts_per_column$Percentage <- rownames(counts_per_column)

percent_stacked <- pivot_longer(counts_per_column, 
                                cols = -Percentage, 
                                names_to = "Precautionary_Measure", 
                                values_to = "Counts")
```
```{r}
ggplot(percent_stacked, 
       aes(x = Precautionary_Measure, 
           y = Counts,
           fill = Percentage)) +
  
  geom_bar(stat = "identity") +
  
  labs(x = "Precautionary Measure", y = "Cumulative Count") +
  
  theme_minimal(base_size = 12) +  
  
  theme(plot.title = element_text(hjust = 0)) +
  
  scale_fill_brewer(palette = "YlGnBu")
```


```{r reactions ~ knowledge}
dd_reaction <- dd[grep("reaction", dd$type), ]
dd_reaction <- dd_reaction[ , c(2,7)]

dd_reaction$qnumber <- sprintf("q%02d", 1:nrow(dd_reaction))

df_reaction <- as.data.frame(df[c(1, 19:28)])
rownames(df_reaction) <- df_reaction$Respondent_ID

reaction_response <- df_reaction[, -1] %>% 
  mutate(
    across(
      .fns = ~ case_when(
        . == "Yes" ~ 0,
        . == "Strongly_Agree" ~ 0,
        . == "Agree" ~ 0,
        . == "Somewhat_Agree" ~ 0,
        . == "No" ~ 1,
        . == "Strongly_Disagree" ~ 1,
        . == "Disagree" ~ 1,
        . == "Somewhat_Disagree" ~ 1,
        . == "Unsure" ~ NA_real_, # 0 in dataframe
        . == "Does_not_apply_to_me" ~ NA_real_
      )
    )
  )

colnames(reaction_response) <- sprintf("q%02d", 1:ncol(reaction_response))

reaction_response[] <- lapply(reaction_response, factor)

dfreact <- cbind(reaction_response, correct_count)

results.react <- list()

for(i in 1:10) {
  
  question_col <- sprintf("q%02d", i)
  
  formula_str <- paste(question_col, "~ correct_count")
  formula_obj <- as.formula(formula_str)
  
  results.react[[question_col]] <- glm(formula = formula_obj, 
                                       data = dfreact,
                                       family = "binomial",
                                       na.action = na.omit)
}

model_react <- data.frame()

for (question_col in names(results.react)) {
  
  glm_model <- results.react[[question_col]]
  
  summary <- tidy(results.react[[question_col]])
  summary$Question <- question_col
  
  model_react <- rbind(model_react, summary)
}

model_rk <- subset(model_react, term != "(Intercept)") # current model calculates the likelihood of answering "no" to questions, influenced by knowledge score. *-1 to inverse, showing likelihood of answering yes
model_rk$estimate <- model_rk$estimate * -1
model_rk$OddsRatio <- exp(model_rk$estimate)
model_rk$LowerCI <- exp(model_rk$estimate) -
  (1.96 * model_rk$std.error)
model_rk$UpperCI <- exp(model_rk$estimate) +
  (1.96 * model_rk$std.error)

model_rk$writtenQ <- c("I would be more likely to research treatment if I learned I was high risk",
                       "Learnig I was high risk wouldn't help much, because treatment options are limited",
                       "It would be upsetting to learn I was high risk from a genetic test, so I am happier not knowing",
                       "If I learnt I had high risk, I would be concerned about my emotional reactions", 
                       "If I learnt I had high risk, I would be concerned about my partner's reaction", 
                       "If I learnt I had high risk, I would be concerned about my family's reaction", 
                       "I would worry whether the genetic test results were accurate", 
                       "I would worry  about how it would affect my health and/or life insurance",
                       "I would worry that it would affect my chances of finding a job", 
                       "Learning I was high risk, would help me plan for the future")

model_rk$stars <-
  sapply(model_rk$p.value, function(p) {
    if (is.na(p))
      return(NA)
    # Find the first instance where the p-value is less than or equal to 'sig' and return the corresponding 'star'
    star <- stat_stars$star[which(p <= stat_stars$sig)[1]]
    if (length(star) == 0)
      ""
    else
      star # If no stars are assigned, return an empty string
  })

```
```{r}
ggplot(model_rk, 
       aes(y = reorder(writtenQ, OddsRatio),
           x = OddsRatio, 
           xmin = LowerCI, 
           xmax = UpperCI)) +
  
  geom_linerange(aes(color = estimate),
                 position = position_dodge(width = 0.2)) +
  
  geom_point(aes(color = estimate),
             size = 2,
             position = position_dodge(width = 0.2)) +
  
  geom_vline(xintercept = 1,
             linetype = 3) +
  
  labs(y = "Questions") +
  
  geom_text(aes(label = stars, 
                y = reorder(writtenQ, OddsRatio)),
            vjust = 0, 
            color = "black", 
            size = 3.8) + 
  
  theme(legend.position = "none",
        plot.title = element_text(hjust = 1.5)) +

  scale_y_discrete(labels = label_wrap_gen(width = 50)) 
```

```{r variant analysis} 
#reaction questions at 1.0 odds ratio most likely to be impacted
cofounders <- df[1:6500, 74:78] %>% 
  mutate(
    across(
      .fns = ~ case_when(
        . == "White_British" ~ "White_All",
        . == "White_Irish" ~ "White_All",
        . == "Any_Other_White_Background" ~ "White_All",
        . == "Black_British" ~ "Black_All",
        . == "Black_Caribbean" ~ "Black_All",
        . == "Black_African" ~ "Black_All",
        . == "Any_Other_Black_Background" ~ "Black_All",
        . == "Asian_British" ~ "Asian_All",
        . == "Asian_Indian" ~ "Asian_All",
        . == "Asian_Pakistani" ~ "Asian_All",
        . == "Asian_Bangladeshi" ~ "Asian_All",
        . == "Chinese" ~ "Asian_All",
        . == "Mixed_White_&_Black" ~ "Mixed_All",
        . == "Mixed_White_and_Asian" ~ "Mixed_All",
        . == "Any_Other_Mixed_Background" ~ "Mixed_All",
        . == "Any_Other_Ethnic_Group" ~ NA_character_,
        . == "Not_Stated" ~ NA_character_,
        . == "Rather_Not_Say" ~ NA_character_,
        . == "Married" ~ "Living_together",
        . == "Cohabiting" ~ "Living_together",
        . == "Catholic" ~ "Religion",
        . == "Christian_other" ~ "Religion",
        . == "Jewish" ~ "Religion",
        . == "Muslim" ~ "Religion",
        . == "Hindu" ~ "Religion",
        . == "Buddhist" ~ "Religion",
        . == "Only_A_Little_Important" ~ "Important",
        . == "Somewhat_Important" ~ "Important",
        . == "Very_Important" ~ "Important",
        . == "Don’t_Know" ~ NA_character_,
        . == "Other" ~ NA_character_,
        TRUE ~ .
        )
      )
    ) 

cofounders[] <- lapply(cofounders, function(x) if(is.character(x)) factor(x) else x)

cofounders$Racial_or_Ethnic_Group <- relevel(cofounders$Racial_or_Ethnic_Group, ref = "White_All")
cofounders$Marital_Status <- relevel(cofounders$Marital_Status, ref = "Single/Never_Married")
cofounders$Religious_Beliefs <- relevel(cofounders$Religious_Beliefs, ref = "No_Religion")
cofounders$`What_Is_The_Impact_Of_Your_Religious_Beliefs_On_Your_Decision_Making?` <- relevel(cofounders$`What_Is_The_Impact_Of_Your_Religious_Beliefs_On_Your_Decision_Making?`, ref = "Not_At_All_Important")

```
```{r}

glm_personal <- summary(glm(as.numeric(reaction_response$q04) ~as.numeric(correct_count) +
                              cofounders$Marital_Status +
                              cofounders$Religious_Beliefs +
                              cofounders$`What_Is_The_Impact_Of_Your_Religious_Beliefs_On_Your_Decision_Making?`)
                        )
summary_personal <- as.data.frame(glm_personal$coefficients)
summary_personal$Term <- rownames(summary_personal)
summary_personal$Significant <- ifelse(summary_personal$`Pr(>|t|)` < 0.05, "Yes", "No")
summary_personal$Question <- "I would be concerned about my emotional reactions"
```
```{r}
glm_partner <- summary(glm(as.numeric(reaction_response$q05) ~as.numeric(correct_count) +
                             cofounders$Marital_Status +
                             cofounders$Religious_Beliefs +
                             cofounders$`What_Is_The_Impact_Of_Your_Religious_Beliefs_On_Your_Decision_Making?`
                           )
                       )
summary_partner <- as.data.frame(glm_partner$coefficients)
summary_partner$Term <- rownames(summary_partner)
summary_partner$Significant <- ifelse(summary_partner$`Pr(>|t|)` < 0.05, "Yes", "No")
summary_partner$Question <- "I would be concerned about my partner's reaction"
```
```{r}
glm_family <- summary(glm(as.numeric(reaction_response$q06) ~as.numeric(correct_count) +
                            cofounders$Marital_Status +
                            cofounders$Religious_Beliefs +
                            cofounders$`What_Is_The_Impact_Of_Your_Religious_Beliefs_On_Your_Decision_Making?`
                          )
                      )
summary_family <- as.data.frame(glm_family$coefficients)
summary_family$Term <- rownames(summary_family)
summary_family$Significant <- ifelse(summary_family$`Pr(>|t|)` < 0.05, "Yes", "No")
summary_family$Question <- "I would be concerned about my family's reaction"
```
```{r}
summary_all_glm <- rbind(summary_personal, summary_partner, summary_family)
summary_all_glm <- subset(summary_all_glm, Significant == "Yes")
summary_all_glm <- subset(summary_all_glm, Term != "(Intercept)")

summary_all_glm$id <- 1:nrow(summary_all_glm)

summary_all_glm$OddsRatio <- exp(summary_all_glm$Estimate)
summary_all_glm$LowerCI <- exp(summary_all_glm$Estimate) - (1.96 * summary_all_glm$`Std. Error`)
summary_all_glm$UpperCI <- exp(summary_all_glm$Estimate) + (1.96 * summary_all_glm$`Std. Error`)
summary_all_glm$cofounder = c(
  "Religious conviction",
  "Married/Cohabitating",
  "Divorced/Seperated",
  "Religious conviction",
  "Religious conviction"
)

summary_all_glm$stars <-
  sapply(summary_all_glm$`Pr(>|t|)`, function(p) {
    if (is.na(p))
      return(NA)
    # Find the first instance where the p-value is less than or equal to 'sig' and return the corresponding 'star'
    star <- stat_stars$star[which(p <= stat_stars$sig)[1]]
    if (length(star) == 0)
      ""
    else
      star # If no stars are assigned, return an empty string
  })

```
```{r}
ggplot(summary_all_glm, aes(y = reorder(cofounder, id),
                            x = OddsRatio,
                            xmin = 0.85,
                            xmax = 1.10)) +
  
  geom_point(aes(color = cofounder),
             size = 3) +
  
  geom_linerange(aes(colour = cofounder,
                     xmin = LowerCI, 
                     xmax = UpperCI)) +
  
  geom_vline(xintercept = 1,
             linetype = 3) +
  
  geom_text(aes(label = stars, 
                y = reorder(cofounder, id)),
            vjust = 0, 
            color = "black", 
            size = 3.8) + 

  
  facet_wrap(~Question, 
             scale = "free",
             nrow = 3) +
  
  labs(y = "Cofounders",
       x = "Odds Ratio") +


  theme(legend.position = "none",
        plot.title = element_text(hjust = 1)) 
```
```{r}
knowledge_cofounders_dd <- dd[53:63, ]

knowledge_cofounders_df <- dfv2[1:6500, c(1, 7:13, 15:18)]
rownames(knowledge_cofounders_df) <- knowledge_cofounders_df$Respondent_ID

knowledge_cofounders <- knowledge_cofounders_df[, -1] %>% 
  mutate(
    across(
      .fns = ~ case_when(
        . == "Strongly_Agree" ~ "Yes",
        . == "Agree" ~ "Yes",
        . == "Somewhat_Agree" ~ "Yes",
        . == "Strongly_Disagree" ~ "No",
        . == "Disagree" ~ "No",
        . == "Somewhat_Disagree" ~ "No",

        . == "Does_not_apply_to_me" ~ NA_character_,
        TRUE ~ .
      )
    )
  ) 
colnames(knowledge_cofounders) <- sprintf("q%02d", 1:ncol(knowledge_cofounders))

knowledge_cofounders[] <- lapply(knowledge_cofounders, factor)
```
```{r}
counts_per_column <- apply(knowledge_cofounders[, -11], 2, table) #q11 Yes=611, No=5889
counts_per_column <- as.data.frame(counts_per_column)
counts_per_column$q11 <- c(5889, 0, 611)

counts_per_column$Answers <- rownames(counts_per_column)
knowledge_cofounders_stacked <- pivot_longer(counts_per_column,
                                             cols = -Answers, 
                                             names_to = "Questions", 
                                             values_to = "Counts")
```





```{r factors affecting knowledge score delete?} 
knowledge_cofounders_dd <- dd[53:63, ]

knowledge_cofounders_df <- dfv2[1:6500, c(1, 7:13, 15:18)]
rownames(knowledge_cofounders_df) <- knowledge_cofounders_df$Respondent_ID

knowledge_cofounders <- knowledge_cofounders_df[, -1] %>% 
  mutate(
    across(
      .fns = ~ case_when(
        . == "Yes" ~ 2,
        . == "Strongly_Agree" ~ 2,
        . == "Agree" ~ 2,
        . == "Somewhat_Agree" ~ 2,
        . == "No" ~ 0,
        . == "Strongly_Disagree" ~ 0,
        . == "Disagree" ~ 0,
        . == "Somewhat_Disagree" ~ 0,
        . == "Unsure" ~ 1,
        . == "Does_not_apply_to_me" ~ NA_real_
      )
    )
  ) #ordered No, Unsure, Yes
colnames(knowledge_cofounders) <- sprintf("q%02d", 1:ncol(knowledge_cofounders))

knowledge_cofounders[] <- lapply(knowledge_cofounders, factor)

counts_per_column <- apply(knowledge_cofounders[, -11], 2, table) #q11 Yes=611, No=5889
counts_per_column <- as.data.frame(counts_per_column)
counts_per_column$q11 <- c(5889, 0, 611)

counts_per_column$Answer <- c("No", "Unsure", "Yes")
#counts_per_column$Answer <- factor(counts_per_column$Answer, levels = c("No", "Usure", "Yes")) #leveling to base of No

knowledge_cofounders_stacked <- pivot_longer(counts_per_column,
                                             cols = -Answer, 
                                             names_to = "Questions", 
                                             values_to = "Counts")
```
```{r}
ggplot(knowledge_cofounders_stacked, 
       aes(x = Questions, 
           y = Counts,
           fill = Answer)) +
  
  geom_bar(stat = "identity") +
  
  labs(x = "Question", 
       y = "Cumulative Count") +
  
  theme_minimal(base_size = 12) +  
  
  scale_fill_brewer(palette = "YlGnBu",
                    direction = -1)

```

```{r}
results_ccf <- list()

for (col_name in names(knowledge_cofounders)) {
  
  formula_str <- paste("correct_count", "~", col_name)
  
  formula_obj <- as.formula(formula_str)
  
  results_ccf[[col_name]] <- glm(formula = formula_obj, 
                                 data = knowledge_cofounders,
                                 family = "poisson",
                                 na.action = na.omit)
}

model_ccf <- data.frame()

for (question_col in names(results_ccf)) {
  
  glm_model <- results_ccf[[question_col]]
  
  summary <- tidy(results_ccf[[question_col]])
  summary$Question <- question_col
  
  model_ccf <- rbind(model_ccf, summary)
}

model_ccf <- subset(model_ccf, term != "(Intercept)")

model_ccf$q_write <- c(
  "I have heard about genetic testing",
  "I have heard about genetic testing",
  "I have had a genetic test",
  "I have had a genetic test",
  "I have been diagnosed with an inherited genetic condition",
  "I have been diagnosed with an inherited genetic condition",
  "I have an inherited genetic abnormality that gives me increased risk for a specific disease",
  "I have an inherited genetic abnormality that gives me increased risk for a specific disease",
  "I have an inherited genetic abnormality that gives me increased risk for cancer",
  "I have an inherited genetic abnormality that gives me increased risk for cancer",
  "I have a relative with an inherited genetic condition",
  "I have a relative with an inherited genetic condition",
  "I have a relative with an inherited genetic abnormality that gives them an increased risk for cancer",
  "I have a relative with an inherited genetic abnormality that gives them an increased risk for cancer",
  "I have been refused a genetic test due to `ineligibility`",
  "I have been refused a genetic test due to `ineligibility`",
  "I paid for a private healthcare genetic test because the NHS denied one to me",
  "I paid for a private healthcare genetic test because the NHS denied one to me",
  "I paid for an over-the-counter genetic test because the NHS denied one to me",
  "I paid for an over-the-counter genetic test because the NHS denied one to me",
  "I have taken an over-the-counter genetic test without the involvement of a healthcare professional"
)
model_ccf$Answer <- c("Unsure", "Yes",
                      "Unsure", "Yes",
                      "Unsure", "Yes",
                      "Unsure", "Yes",
                      "Unsure", "Yes",
                      "Unsure", "Yes",
                      "Unsure", "Yes",
                      "Unsure", "Yes",
                      "Unsure", "Yes",
                      "Unsure", "Yes",
                      "Yes")

model_ccf$Significant <- ifelse(model_ccf$p.value < 0.05, "Yes", "No")

model_ccf_cut <- subset(model_ccf, Significant == "Yes")

model_ccf_cut$stars <-
  sapply(model_ccf_cut$p.value, function(p) {
    if (is.na(p))
      return(NA)
    # Find the first instance where the p-value is less than or equal to 'sig' and return the corresponding 'star'
    star <- stat_stars$star[which(p <= stat_stars$sig)[1]]
    if (length(star) == 0)
      ""
    else
      star # If no stars are assigned, return an empty string
  })

model_ccf_cut$OddsRatio <- exp(model_ccf_cut$estimate)
model_ccf_cut$LowerCI <- exp(model_ccf_cut$estimate) - (1.96 * model_ccf_cut$std.error)
model_ccf_cut$UpperCI <- exp(model_ccf_cut$estimate) + (1.96 * model_ccf_cut$std.error)

```
```{r}
ggplot(model_ccf_cut, 
       aes(y = q_write,
           x = OddsRatio, 
           xmin = LowerCI, 
           xmax = UpperCI)) +
  
  geom_linerange(aes(color = Answer),
                 position = position_dodge2(width = 1)) +
  
  geom_point(aes(color = Answer),
             size = 2,
             position = position_dodge2(width = 1)) +
  
  geom_vline(xintercept = 1,
             linetype = 3) +
  
  geom_text(aes(label = stars, 
                y = q_write),
            position = position_dodge2(width = 1),
            vjust = 0, 
            color = "black", 
            size = 3.8) + 
  
  labs(y = "Questions") +
  
  theme(plot.title = element_text(hjust = 1)) +

  scale_y_discrete(labels = label_wrap_gen(width = 50))

#estimate is the change in knowledge score when a `no` answer changes to a `yes`
```

